$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$modelBaseName = "haikou-guide-simple-entity-class-diagram"
$qeaPath = Join-Path $scriptDir "$modelBaseName.qea"
$eapxPath = Join-Path $scriptDir "$modelBaseName.eapx"
$pngPath = Join-Path $scriptDir "08_simple_entity_class_diagram.png"
$eaExePath = "D:\EA.exe"

function Move-ExistingFileToBackup {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) { return }

  $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $directory = Split-Path -Parent $Path
  $name = [System.IO.Path]::GetFileNameWithoutExtension($Path)
  $extension = [System.IO.Path]::GetExtension($Path)
  $backupPath = Join-Path $directory "$name.$timestamp.bak$extension"
  Move-Item -LiteralPath $Path -Destination $backupPath
  Write-Host "Backed up old file: $backupPath"
}

function Get-RootModel {
  param($Repository)
  if ($Repository.Models.Count -gt 0) { return $Repository.Models.GetAt(0) }

  $model = $Repository.Models.AddNew("Model", "Package")
  [void]$model.Update()
  $Repository.Models.Refresh()
  return $model
}

function Add-Package {
  param($ParentPackage, [string]$Name)
  $package = $ParentPackage.Packages.AddNew($Name, "")
  [void]$package.Update()
  $ParentPackage.Packages.Refresh()
  return $package
}

function Add-Class {
  param(
    $Package,
    [hashtable]$Registry,
    [string]$Key,
    [string]$Name,
    [string[]]$Attributes
  )

  $element = $Package.Elements.AddNew($Name, "Class")
  $element.Stereotype = "entity"
  [void]$element.Update()

  foreach ($attributeSpec in $Attributes) {
    $parts = $attributeSpec.Split(":", 2)
    $type = ""
    if ($parts.Length -gt 1) { $type = $parts[1] }
    $attribute = $element.Attributes.AddNew($parts[0], $type)
    $attribute.Visibility = "Public"
    [void]$attribute.Update()
  }

  $element.Attributes.Refresh()
  [void]$element.Update()
  $Package.Elements.Refresh()
  $Registry[$Key] = $element
  return $element
}

function Add-Note {
  param($Package, [hashtable]$Registry, [string]$Key, [string]$Text)
  $note = $Package.Elements.AddNew("Relation Type Notes", "Note")
  $note.Notes = $Text
  [void]$note.Update()
  $Package.Elements.Refresh()
  $Registry[$Key] = $note
  return $note
}

function Add-DiagramObject {
  param($Diagram, $Element, [int]$Left, [int]$Top, [int]$Width, [int]$Height)
  $style = "l=$Left;r=$($Left + $Width);t=$Top;b=$($Top - $Height);"
  $diagramObject = $Diagram.DiagramObjects.AddNew($style, "")
  $diagramObject.ElementID = $Element.ElementID
  [void]$diagramObject.Update()
  $Diagram.DiagramObjects.Refresh()
  return $diagramObject
}

function Add-Connector {
  param(
    $Diagram,
    $Source,
    $Target,
    [string]$Type,
    [string]$Name = "",
    [string]$SourceRole = "",
    [string]$TargetRole = "",
    [string]$SourceCard = "",
    [string]$TargetCard = ""
  )

  $connector = $Source.Connectors.AddNew($Name, $Type)
  $connector.SupplierID = $Target.ElementID
  if ($SourceRole) { $connector.ClientEnd.Role = $SourceRole }
  if ($TargetRole) { $connector.SupplierEnd.Role = $TargetRole }
  if ($SourceCard) { $connector.ClientEnd.Cardinality = $SourceCard }
  if ($TargetCard) { $connector.SupplierEnd.Cardinality = $TargetCard }
  try { $connector.Direction = "Source -> Destination" } catch {}
  [void]$connector.Update()
  $Source.Connectors.Refresh()

  try {
    $link = $Diagram.DiagramLinks.AddNew("", "")
    $link.ConnectorID = $connector.ConnectorID
    [void]$link.Update()
    $Diagram.DiagramLinks.Refresh()
  } catch {}

  return $connector
}

function New-EaModelFile {
  param($Repository, [string]$PrimaryPath, [string]$FallbackPath)

  Move-ExistingFileToBackup -Path $PrimaryPath
  Move-ExistingFileToBackup -Path $FallbackPath

  try {
    if ([bool]$Repository.CreateModel(0, $PrimaryPath, 0)) { return $PrimaryPath }
  } catch {
    Write-Host "Create .qea failed, trying .eapx: $($_.Exception.Message)"
  }

  if (-not [bool]$Repository.CreateModel(0, $FallbackPath, 0)) {
    throw "EA CreateModel failed."
  }
  return $FallbackPath
}

function Build-SimpleEntityClassModel {
  param($Repository)

  $root = Get-RootModel -Repository $Repository
  $modelPackage = Add-Package -ParentPackage $root -Name "Haikou Guide Simple Entity Class Model"
  $modelPackage.Notes = "Generated by create-simple-entity-class-diagram-ea.ps1 through Enterprise Architect COM."
  [void]$modelPackage.Update()

  $classPackage = Add-Package -ParentPackage $modelPackage -Name "Simple Entity Model"
  $diagram = $classPackage.Diagrams.AddNew("08 Simple Entity Class Diagram", "Logical")
  $diagram.Notes = "A simple entity class diagram. Connector names mark relation types."
  $diagram.cx = 1260
  $diagram.cy = 760
  [void]$diagram.Update()
  $classPackage.Diagrams.Refresh()

  $r = @{}
  Add-Class -Package $classPackage -Registry $r -Key "User" -Name "User" -Attributes @(
    "id:int", "username:String", "phone:String", "avatarUrl:String"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "Admin" -Name "Admin" -Attributes @(
    "adminPhone:String"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "Place" -Name "Place" -Attributes @(
    "id:String", "name:String", "type:String", "lat:Decimal", "lng:Decimal"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "RecommendedPlace" -Name "RecommendedPlace" -Attributes @(
    "description:Text", "imageUrls:JSON", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "Favorite" -Name "Favorite" -Attributes @(
    "id:int", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "PlaceLike" -Name "PlaceLike" -Attributes @(
    "id:int", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "Comment" -Name "Comment" -Attributes @(
    "id:int", "content:Text", "imageUrls:JSON", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "CommentLike" -Name "CommentLike" -Attributes @(
    "id:int", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "ForumPost" -Name "ForumPost" -Attributes @(
    "id:int", "content:Text", "imageUrls:JSON", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "ForumComment" -Name "ForumComment" -Attributes @(
    "id:int", "content:Text", "imageUrls:JSON", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "Notification" -Name "Notification" -Attributes @(
    "id:int", "type:String", "content:Text", "isRead:Boolean", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "Feedback" -Name "Feedback" -Attributes @(
    "id:int", "content:Text", "status:String", "adminReply:Text", "createdAt:DateTime"
  ) | Out-Null
  Add-Class -Package $classPackage -Registry $r -Key "BadgeGrant" -Name "BadgeGrant" -Attributes @(
    "id:int", "badgeName:String", "isActive:Boolean", "grantedAt:DateTime"
  ) | Out-Null
  Add-Note -Package $classPackage -Registry $r -Key "Legend" -Text "Relation types: Generalization = inheritance; Composition = whole owns parts and parts depend on whole; Aggregation = weak ownership/collection; Association = normal business link." | Out-Null

  Add-DiagramObject -Diagram $diagram -Element $r["User"] -Left 45 -Top 650 -Width 185 -Height 115 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["Admin"] -Left 45 -Top 480 -Width 185 -Height 90 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["Place"] -Left 330 -Top 650 -Width 205 -Height 125 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["RecommendedPlace"] -Left 610 -Top 650 -Width 225 -Height 110 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["Favorite"] -Left 330 -Top 470 -Width 170 -Height 85 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["PlaceLike"] -Left 525 -Top 470 -Width 170 -Height 85 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["Comment"] -Left 850 -Top 650 -Width 215 -Height 120 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["CommentLike"] -Left 1080 -Top 650 -Width 170 -Height 85 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["ForumPost"] -Left 330 -Top 280 -Width 220 -Height 115 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["ForumComment"] -Left 610 -Top 280 -Width 220 -Height 115 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["Notification"] -Left 850 -Top 280 -Width 230 -Height 120 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["Feedback"] -Left 45 -Top 250 -Width 220 -Height 120 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["BadgeGrant"] -Left 45 -Top 75 -Width 220 -Height 110 | Out-Null
  Add-DiagramObject -Diagram $diagram -Element $r["Legend"] -Left 330 -Top 75 -Width 520 -Height 90 | Out-Null

  Add-Connector -Diagram $diagram -Source $r["Admin"] -Target $r["User"] -Type "Generalization" -Name "Generalization" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["RecommendedPlace"] -Target $r["Place"] -Type "Generalization" -Name "Generalization" | Out-Null

  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["RecommendedPlace"] -Type "Association" -Name "Association: publishes" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["Favorite"] -Type "Aggregation" -Name "Aggregation: favorite records" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["Place"] -Target $r["Favorite"] -Type "Association" -Name "Association: favorited place" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["PlaceLike"] -Type "Aggregation" -Name "Aggregation: place like records" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["Place"] -Target $r["PlaceLike"] -Type "Association" -Name "Association: liked place" -SourceCard "1" -TargetCard "0..*" | Out-Null

  Add-Connector -Diagram $diagram -Source $r["Place"] -Target $r["Comment"] -Type "Composition" -Name "Composition: owns comments" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["Comment"] -Type "Association" -Name "Association: writes" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["Comment"] -Target $r["Comment"] -Type "Association" -Name "Association: replies" -SourceRole "parent" -TargetRole "child" -SourceCard "0..1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["CommentLike"] -Type "Aggregation" -Name "Aggregation: comment like records" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["Comment"] -Target $r["CommentLike"] -Type "Association" -Name "Association: liked comment" -SourceCard "1" -TargetCard "0..*" | Out-Null

  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["ForumPost"] -Type "Association" -Name "Association: posts" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["ForumPost"] -Target $r["ForumComment"] -Type "Composition" -Name "Composition: contains comments" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["ForumComment"] -Type "Association" -Name "Association: writes forum comments" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["ForumComment"] -Target $r["ForumComment"] -Type "Association" -Name "Association: nested replies" -SourceRole "parent" -TargetRole "child" -SourceCard "0..1" -TargetCard "0..*" | Out-Null

  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["Notification"] -Type "Association" -Name "Association: receives" -SourceRole "receiver" -TargetRole "notification" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["Notification"] -Type "Association" -Name "Association: triggers" -SourceRole "sender" -TargetRole "notification" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["Feedback"] -Type "Association" -Name "Association: submits" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["Admin"] -Target $r["Feedback"] -Type "Association" -Name "Association: handles" -SourceCard "0..1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["Admin"] -Target $r["BadgeGrant"] -Type "Association" -Name "Association: grants" -SourceCard "1" -TargetCard "0..*" | Out-Null
  Add-Connector -Diagram $diagram -Source $r["User"] -Target $r["BadgeGrant"] -Type "Aggregation" -Name "Aggregation: badge grants" -SourceCard "1" -TargetCard "0..*" | Out-Null

  [void]$diagram.Update()
  $Repository.SaveDiagram($diagram.DiagramID)
  $Repository.ReloadDiagram($diagram.DiagramID)
  $Repository.RefreshModelView($modelPackage.PackageID)
  return $diagram
}

$repository = $null
try {
  $repository = New-Object -ComObject EA.Repository
  $modelPath = New-EaModelFile -Repository $repository -PrimaryPath $qeaPath -FallbackPath $eapxPath
  [void]$repository.OpenFile($modelPath)
  $diagram = Build-SimpleEntityClassModel -Repository $repository

  $project = $repository.GetProjectInterface()
  $diagramGuidXml = $project.GUIDtoXML($diagram.DiagramGUID)
  [void]$project.PutDiagramImageToFile($diagramGuidXml, $pngPath, 1)
  [void]$repository.CloseFile()
  [void]$repository.Exit()
  $repository = $null

  if (Test-Path -LiteralPath $eaExePath) {
    Start-Process -FilePath $eaExePath -ArgumentList "`"$modelPath`"" -WindowStyle Normal | Out-Null
  } else {
    Start-Process -FilePath $modelPath -WindowStyle Normal | Out-Null
  }

  Write-Host "EA model file: $modelPath"
  Write-Host "Exported diagram image: $pngPath"
  Write-Host "Diagram name: 08 Simple Entity Class Diagram"
} finally {
  if ($repository -ne $null) {
    try { [void]$repository.CloseFile() } catch {}
    try { [void]$repository.Exit() } catch {}
  }
}
